dataset: 
  image_dir: data\train_images
  csv_path: data\meta_train.csv
  label_type: age
  batch_size: 32
  image_size: 224
  val_size: 0.2
  oversample: False

train:
  epochs: 10
  lr: 0.0001
  model_name: "baseline_model"
  checkpoint_dir: "checkpoints/age"
  patience: 5
  early_stopping: True
  force_cpu: True
  model: "baseline"


